const words = [
    'if',
    'athlete',
    'apple',
    'border',
    'characteristic',
    'tree',
    'beer',
    'conceive',
    'disturbance',
    'inspector',
    'pattern',
    'authorise',
    'expertise',
    'executrix',
    'total',
    'follow',
    'superintendent',
    'humor',
    'self',
    'diagram',
    'supplementary',
    'teenager',
    'shy',
    'shrink',
    'pavement',
    'cotton',
    'cluster',
    'quaint',
    'lump',
    'marketing',
    'culture',
    'scramble',
    'clarify',
    'makeup',
    'bear',
    'restrict',
    'endure',
    'plan',
    'slot',
    'board',
    'fraud',
    'computing',
    'park',
    'heal',
    'ash',
    'crystal',
    'deport',
    'extend',
    'soil',
    'offense',
];

export default function dummyApiCall(text, size) {
    return new Promise((resolve) => {
        setTimeout(() => {
            resolve(words.filter(w => w.startsWith(text)).slice(0, size))
        },Math.random*100)
    })
}